---
- hosts: all
  become: yes
  roles:
    - role: prep
    - role: geerlingguy.java
    - role: geerlingguy.elasticsearch
    - role: geerlingguy.logstash
    - role: geerlingguy.nginx
    - role: geerlingguy.kibana
    - role: ufw
    # - role: geerlingguy.certbot
