---
- src: geerlingguy.java
  version: 1.9.5
- src: geerlingguy.elasticsearch
  version: 3.0.1
- src: geerlingguy.logstash
  version: 4.0.0
- src: geerlingguy.kibana
  version: 3.2.1
- src: geerlingguy.nginx
  version: 2.7.0
- src: geerlingguy.certbot
  version: 3.0.2
